### ISSUE TITLE
Default image on img.steemconnect.com breaks SSL

### ISSUE THREAD

**Issue by Netherdrake** [adcpm/steemconnect.com#102]
If the image is of an unknown account, ie:
https://img.steemconnect.com/@sdfsdfasdgs/?s=72

It will resolve to:
http://res.cloudinary.com/hln3kqm5p/image/upload/c_fill,h_72,w_72/%40steemconnect

Which is HTTP and thus breaks SSL seal.

**Comment by mynameisek** [comment]
@nil1511

**Comment by nil1511** [comment]
@Netherdrake Thanks for reporting. this issue is now fixed.
