### ISSUE TITLE
Long permalinks break the dashboard

### ISSUE THREAD

**Issue by yamadapc** [adcpm/steemconnect.com#31]
<img width="721" alt="screen shot 2016-09-14 at 11 54 58" src="https://cloud.githubusercontent.com/assets/3923654/18517269/1ee91d60-7a72-11e6-8a4a-1608dfa2daf7.png">

**Comment by adcpm** [comment]
Styling not set yet for this page. Will work on it

**Comment by yamadapc** [comment]
Did you fix this?

**Comment by adcpm** [comment]
No. I will have a wireframe of the dashboard soon.

**Comment by adcpm** [comment]
We now using different layout, this concern is not relevant anymore.
