### ISSUE TITLE
API route api/getAccount is useless

### ISSUE THREAD

**Issue by adcpm** [adcpm/steemconnect.com#49]
Why do we need this route http://prntscr.com/cngjyp ? We could make the call directly on front-end with Steem.js.

**Comment by nil1511** [comment]
This call can be made using front-end. All apis calls are made using steemconnect backend so just following the pattern.

**Comment by adcpm** [comment]
We need this front-end

**Comment by nil1511** [comment]
removed in 2cb24dece998beb285f96d611c2c4e83ee852433
