### ISSUE TITLE
GetAccount request is throwing an error on localhost

### ISSUE THREAD

**Issue by adcpm** [adcpm/steemconnect.com#50]
See the screenshot: http://prntscr.com/cngjyp . The repo in local throwing an error, it seem that the request from localhost is sent to steemconnect and the sameorigin rule dont allow this.

**Comment by nil1511** [comment]
can you post the request url with origin and refer header during the error?

**Comment by nil1511** [comment]
removed getAccount in 2cb24dece998beb285f96d611c2c4e83ee852433
