### ISSUE TITLE
API - Bug in /api/verify ?

### ISSUE THREAD

**Issue by yamadapc** [adcpm/steemconnect.com#69]
I'm trying to understand `verifyAuth` and `verifyToken` support for each other.

On `verifyAuth`, the JWT may be read from the `auth` cookie or an authentication header, yet on `verifyToken` it's read from the querystring or a `x-steemconnect-token` header.

What are the modes of authentication here? Why are they different? `verifyToken` is for 3rd party applications?

It seems easier to me to set the JWT as a cookie on the responses and read from it everywhere.

**Comment by yamadapc** [comment]
https://github.com/adcpm/steemconnect.com/blob/dev/routes/middleware.js#L8-L48

**Comment by nil1511** [comment]
`verifyAuth` only stores encrypted username and postwif on steemconnect.com's cookie. while `verifyToken` is jwt token containing appname and username.
