### ISSUE TITLE
Allow local url on dev mode

### ISSUE THREAD

**Issue by adcpm** [adcpm/steemconnect.com#87]

**Comment by nil1511** [comment]
close in 34292e7

**Comment by adcpm** [comment]
redirect_url should be optional on login and redirect to referrer by default. Actually i'm stuck on login if i'm using file:// url

**Comment by nil1511** [comment]
App should save atleast one redirect urls. dev mode should allow local origin and not change any redirection flow.

**Comment by adcpm** [comment]
Production app will have at least 1 redirect url saved. But it should not be mandatory to add redirect_url parameter, it should be referrer URL by default if matching the redirect_url saved. On dev mode it can be referrer URL even if no url is saved for the app on Postgres
